run:
  deadline: 5m

issues:
  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0
  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 0

  # We want to try and improve the comments in the k6 codebase, so individual
  # non-golint items from the default exclusion list will gradually be added
  # to the exclude-rules below
  exclude-use-default: false

  exclude-rules:
  # Exclude duplicate code and function length and complexity checking in test
  # files (due to common repeats and long functions in test code)
    - path: _(test|gen)\.go
      linters:
        - cyclop
        - dupl
        - gocognit
        - funlen
        - lll
    - linters:
      - staticcheck # Tracked in https://github.com/grafana/xk6-grpc/issues/14
      text: "The entire proto file grpc/reflection/v1alpha/reflection.proto is marked as deprecated."

linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  govet:
    check-shadowing: true
  cyclop:
    max-complexity: 25
  maligned:
    suggest-new: true
  dupl:
    threshold: 150
  goconst:
    min-len: 10
    min-occurrences: 4
  funlen:
    lines: 80
    statements: 60
  forbidigo:
    forbid:
      - '^(fmt\\.Print(|f|ln)|print|println)$'
      # Forbid everything in syscall except the uppercase constants
      - '^syscall\.[^A-Z_]+$(# Using anything except constants from the syscall package is forbidden )?'
      - '^logrus\.Logger$'
  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: true
  stylecheck:
    checks:
      - "all"
      - '-ST1000' # Use of underscores in Go names

linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - cyclop
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - importas
    - ineffassign
    - interfacebloat
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - nosprintfhostport
    - paralleltest
    - prealloc
    - predeclared
    - promlinter
    - revive
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - wastedassign
    - whitespace
  fast: false